# Generated by Django 4.0.3 on 2022-04-26 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to=user.models.product_picture_uploader)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('fruta', 'FRUTA'), ('legume', 'LEGUME'), ('verdura', 'VERDURA')], max_length=255)),
                ('amount', models.IntegerField()),
                ('amount_type', models.CharField(choices=[('kg', 'KG'), ('unidade', 'UNIDADE')], max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'CLIENTE'), ('produtor', 'PRODUTOR')], default='cliente', max_length=255),
        ),
        migrations.CreateModel(
            name='UserFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to=user.models.farm_picture_uploader)),
                ('cep', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('DF', 'distrito federal'), ('SP', 'são paulo')], default='DF', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.BigIntegerField()),
                ('seller', models.BigIntegerField()),
                ('amount_buy', models.IntegerField()),
                ('buyer_review', models.IntegerField(blank=True, null=True)),
                ('seller_review', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('finalizado', 'FINALIZADO'), ('andamento', 'ANDAMENTO')], max_length=255)),
                ('date_buy', models.DateField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.farmproduct')),
            ],
        ),
        migrations.AddField(
            model_name='farmproduct',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
