site_name: DaTerra
repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-DaTerra
repo_name: ''

theme:
  name: material
  language: 'pt'
  logo: 'img\logoprovisoria.png'
  favicon: 'img\logoprovisoria.png'
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: green
    
extra_css:
  - _extra/extra.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Início: index.md
  - Unidade 1:  
    - Declaração do Problema: DeclaracaoProblema.md
    - Abordagem de Desenvolvimento de Software: AbordagemDev.md
    - Abordagem de engenharia de Requisitos: AbordagemEngReq.md
    - Lições Aprendidas: LicoesAprendidas.md
  - Unidade 2:
    - Requisitos: RequisitosF.md
    - Canvas MVP: canvasmvp.md
    - Personas: personasunidade2.md
    - Atualização da Abordagem: AbordagemEngReq2.md
    - Visão Geral do Projeto: Vsprojeto.md
  - Organização:
    - Reuniões: reunioes.md
    - Sprints: sprints.md
  - Resultados: resultados.md

plugins:
  - mkdocs-video
