site_name: DaTerra
repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-DaTerra
repo_name: ''

theme:
  name: material
  language: 'pt'
  logo: 'img\logoprovisoria.png'
  favicon: 'img\logoprovisoria.png'
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: green
    
extra_css:
  - _extra/extra.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Início: index.md
  - Unidade 1:  
    - Declaração do Problema: DeclaracaoProblema.md
    - Abordagem de Desenvolvimento de Software: AbordagemDev.md
    - Abordagem de engenharia de Requisitos: AbordagemEngReq.md
    - Lições Aprendidas: LicoesAprendidas.md
  - Unidade 2:
    - Visão Geral do Produto:
      - Requisitos: RequisitosF.md
      - Personas: personasunidade2.md
      - Canvas MVP: canvasmvp.md
    - Engenharia de Requisitos: AbordagemEngReq2.md
    - Visão Geral do Projeto: Vsprojeto.md
    - Lições Aprendidas: licoesunidade2.md
  - Unidade 3:
    - Visão Geral do Produto:
      - PBB: pbb.md
      - Histórias de Usuário: pbb_historias.md
      - BDD: bdd.md
  - Unidade 4:
    - Visão Geral do Projeto: Vsprojeto2.md
  - Resultados: resultados.md

plugins:
  - mkdocs-video
