site_name: DaTerra
repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-DaTerra
repo_name: ''

theme:
  name: material
  language: 'pt'
  logo: ''
  favicon: ''
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Inicio: index.md
  - Documento Visão: DocVisao.md
  - Reuniões: reunioes.md